### ISSUE TITLE
the docker run command fails

### ISSUE THREAD

**Issue by widdiot** [UFAL-DSG/pykaldi#30]
Terminal output:

sudo docker run ufaldsg/pykaldi /bin/bash -c "cd online_demo; make gmm-latgen-faster; make online-recogniser; make pyonline-recogniser"
mkdir -p decode
mkdir -p `dirname data/vystadial-sample-en.tar.gz` 
wget http://vystadial.ms.mff.cuni.cz/download/pykaldi/egs/vystadial/online_demo//data/vystadial-sample-en.tar.gz -O data/vystadial-sample-en.tar.gz
--2020-02-03 12:19:02--  http://vystadial.ms.mff.cuni.cz/download/pykaldi/egs/vystadial/online_demo//data/vystadial-sample-en.tar.gz
Resolving vystadial.ms.mff.cuni.cz (vystadial.ms.mff.cuni.cz)... 195.113.20.160
Connecting to vystadial.ms.mff.cuni.cz (vystadial.ms.mff.cuni.cz)|195.113.20.160|:80... ^[[Zfailed: Connection timed out.
Retrying.

**Comment by tuetschek** [comment]
I'm sorry, this software is not supported anymore. This command would have downloaded the sample models, but the server has been down for a few years already.
